# Rasper services
services:
  raspar-api:
    container_name: raspar
    build: ./
    user: "node"
    command: npm run dev
    working_dir: /home/src/raspar
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/src/raspar
      - ./temp:/home/node/.npm
      - ./temp:/tmp
